on:
  schedule:
  - cron: "0 0 * * *"
  push:
    branches:
      - master

name: update-data

jobs:
  render:
    name: update-data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown, remotes, and the local package
        run: |
          install.packages("remotes")
          remotes::install_local(".")
          remotes::install_cran("usethis")
          remotes::install_cran("rmarkdown")
        shell: Rscript {0}
      - name: Execute Script
        run: |
          Rscript data-raw/atualizar_sorteios.R
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/.
          git add inst/extdata/.
          git add README.md
          git add README.Rmd
          git commit -m 'sorteios atualizados' || echo "sorteios atualizados"
          git push origin || echo "sorteios atualizados"
